esphome:
  name: "esphomeesp32mb02"
  friendly_name: ESPHomeESP32MB02


esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "yzAaS9yshXtRbnTyziFSulTlhwqHaRGyViyXB3+j/rs="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-2C2Aa8"
    password: "0hkvBu4ahqAY"

captive_portal:

uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1
  parity: none
  data_bits: 8

#Modbus Sensor & Modbus Relay
modbus:
  flow_control_pin: 5
  id: modbus_sensor

modbus_controller:
# Modbus device addr slave id1 
  - id: xymd02_01
    address: 0x1
    modbus_id: modbus_sensor
    command_throttle: 200ms
    setup_priority: -10
    update_interval: 10s

# Modbus device addr slave id2
  - id: mbid2
    address: 0x2
    modbus_id: modbus_sensor
    setup_priority: -10
    update_interval: 5s

sensor:
  # Modbus device addr slave id1
    #TEMP sensor
  - platform: modbus_controller
    modbus_controller_id: xymd02_01
    id: temperature2
    name: "TEMP2"
    device_class: TEMPERATURE
    address: 0x001
    unit_of_measurement: "°C"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1
  #HUMI sensor
  - platform: modbus_controller
    modbus_controller_id: xymd02_01
    id: humidity2
    name: "HUMI2"
    device_class: HUMIDITY
    address: 0x002
    unit_of_measurement: "%"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1  
      
switch:
# Modbus device addr slave id2
  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW1
    name: "SW1"
    address: 0x00
    register_type: coil
    bitmask: 0xFF

  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW2
    name: "SW2"
    address: 0x01
    register_type: coil
    bitmask: 0xFF

  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW3
    name: "SW3"
    address: 0x02
    register_type: coil
    bitmask: 0xFF

  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW4
    name: "SW4"
    address: 0x03
    register_type: coil
    bitmask: 0xFF

  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW5
    name: "SW5"
    address: 0x04
    register_type: coil
    bitmask: 0xFF

  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW6
    name: "SW6"
    address: 0x05
    register_type: coil
    bitmask: 0xFF

  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW7
    name: "SW7"
    address: 0x06
    register_type: coil
    bitmask: 0xFF

  - platform: modbus_controller
    modbus_controller_id: mbid2
    id: SW8
    name: "SW8"
    address: 0x07
    register_type: coil
    bitmask: 0xFF



