esphome:
  name: esphome-web-bbd3d0
  friendly_name: ESPHome Web bbd3d0

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MaifsuuKWJ1E+Hoe8SJuT8BSU/WmRwtGMkqz96NdpIw="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Bbd3D0"
    password: "mbkLDM1unRhO"

captive_portal:
# หลังจากที่เพิ่ม Devices ผ่าน ESPHome เรียบร้อยแล้วให้คัดลอกเริ่มตั้งแต่บรรทัดที่ 33 เป็นต้นไปเอาไปใส่ในไฟล์ .yaml ของ Devices 
# ใน ESPHome บันทึกและ Install
uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1
  parity: none

#XY-MD02 Temperature & Humidity Sensor
modbus:
  flow_control_pin: 5
  id: modbus_sensor

modbus_controller:
## the Modbus device addr slave id1
  - id: xymd02_01
    address: 0x1
    modbus_id: modbus_sensor
    command_throttle: 200ms
    setup_priority: -10
    update_interval: 5s

# 4 CH Relay
switch:
  - platform: gpio
    name: "Switch 1"
    pin: 25

  - platform: gpio
    name: "Switch 2"
    pin: 26
    
  - platform: gpio
    name: "Switch 3"
    pin: 33
    
  - platform: gpio
    name: "Switch 4"
    pin: 32
# Digital & Analog Sensor
sensor:
  #DHT11/DHT22
  - platform: dht
    pin: 18
    temperature:
      name: "DHT11/DHT22 Temperature"
    humidity:
      name: "DHT11/DHT22 Humidity"
    update_interval: 10s
  
  #SoilMoisture Sensor
  - platform: adc
    pin: 35
    
    filters:
      - lambda: |-
          if (x > 3.15) {
            return 0;
          } else if (x < 1.30) {
            return 100;
          } else {
            return (3.15-x) / (3.15-1.30) * 100.0;
          }
    name: "Soil Moisture Level"
    unit_of_measurement: "%"
    device_class: humidity
    icon: "mdi:watering-can"
    update_interval: 10s
    attenuation: auto
    accuracy_decimals: 0

  ## the Modbus device addr slave id1
  #TEMP sensor
  - platform: modbus_controller
    modbus_controller_id: xymd02_01
    id: temperature
    name: "TEMP"
    device_class: TEMPERATURE
    address: 0x001
    unit_of_measurement: "°C"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1
  #HUMI sensor
  - platform: modbus_controller
    modbus_controller_id: xymd02_01
    id: humidity
    name: "HUMI"
    device_class: HUMIDITY
    address: 0x002
    unit_of_measurement: "%"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1  
