alias: PEA Save Previous Billing Cycle
description: >
  บันทึกหน่วยไฟ (kWh) และค่าไฟรวมของรอบบิล PEA ที่ผ่านมา ก่อนตัดรอบบิล
  (คืนวันที่ 15)
triggers:
  - trigger: time
    at: "23:59:50"
conditions:
  - condition: template
    value_template: "{{ now().day == 15 }}"
actions:
  - action: input_number.set_value
    target:
      entity_id: input_number.pea_prev_bill_kwh
    data:
      value: "{{ states('sensor.monthly_energy_pea') | float(0) | round(4) }}"
  - action: input_number.set_value
    target:
      entity_id: input_number.pea_prev_bill_total
    data:
      value: "{{ states('sensor.total_cost') | float(0) | round(2) }}"
mode: single
